trigger:
  branches:
    include:
      - master
pool:
  vmImage: 'macos-latest'

variables:
  - group: ios-pipeline

steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'development.cer'
      certPwd: 'Admin@123'
      keychain: 'temp'
      deleteCert: true
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: '$(provisioningProfile)'
      removeProfile: true
  
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '18.12.1' # you can use your desired version here
      # workingDirectory: 'app-rn/'
  - script: yarn install
    displayName: Install Dependencies
  - task: CocoaPods@0
    displayName: 'Install CocoaPods'
    inputs:
      workingDirectory: './ios'
  - task: Xcode@5
    displayName: 'Build IPA'
    inputs:
      actions: 'build'
      configuration: 'Release'
      sdk: 'iphoneos'
      xcWorkspacePath: './ios/AwesomeProject.xcworkspace'
      scheme: 'AwesomeProject'
      packageApp: true
      exportPath: 'output'
      signingOption: 'manual'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'

  - task: CopyFiles@2
    displayName: 'Copy IPA'
    inputs:
      contents: '**/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
      overWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(build.artifactStagingDirectory)/output/$(sdk)/$(configuration)' 
      artifactName: 'drop' 
      publishLocation: 'Container'
